# Generated by Django 5.2.10 on 2026-01-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='intent',
            field=models.CharField(choices=[('mentor_me', "I'd like mentorship"), ('collaborate', "Let's collaborate"), ('peer_network', 'Peer networking')], default='peer_network', max_length=20),
        ),
    ]
