# Generated by Django 5.2.10 on 2026-01-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_profile_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("founder", "Founder"), ("mentor", "Mentor")],
                default="",
                max_length=10,
            ),
        ),
    ]
